name: updater
on:
  push:
    branches:
      - master
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: fifsky/ssh-action@master
        with:
          command: cd /root/redstone-emojis && bash update.sh
          host: topred.fr # Amazing redstone server. Come check us out :)
          args: "-tt -vvv"
          key: ${{secrets.SSH_PRIVATE_KEY}}
          pass: ${{secrets.SSH_PASSPHRASE}}
