name: updater
on:
  push:
    branches:
      - master
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: garygrossgarten/github-action-ssh@v0.6.3
        env:
          SSH_PASSPHRASE: ${{secrets.SSH_PASSPHRASE}}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_USERNAME: ${{secrets.SSH_USERNAME}}
        with:
          command: cd /root/redstone-emojis && bash update.sh
          host: topred.fr # Amazing redstone server. Come check us out :)
          username: ${{env.SSH_USERNAME}}
          privateKey: ${{env.SSH_PRIVATE_KEY}}
          passphrase: ${{env.SSH_PASSPHRASE}}
